version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_LISTENERS: LISTENER_EXTERNAL://kafka:9092,LISTENER_INTERNAL://kafka:29092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_EXTERNAL://localhost:9092,LISTENER_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_EXTERNAL:PLAINTEXT, LISTENER_INTERNAL:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock