meshinery:
  core:
    inject:
      - "ask.me.again.meshinery.example.entities.VotingContext"
    shutdown-on-finished: false
    graceful-shutdown-on-error: false
  draw:
    resolution: 'HD720'
  connectors:
    mysql:
      limit: 10
      password: 'password'
      user: 'user'
      connection-string: 'jdbc:mysql://localhost:3306/db?useSSL=false&allowPublicKeyRetrieval=true'